### ISSUE TITLE
Compiling with warnings breaks interaction page

### ISSUE THREAD

**Issue by Cygnusfear** [SuperblocksHQ/superblocks-lab#102]
## Environment/Browser
Chrome latest

## Description
Not setting pure on lolWut function breaks contract interaction

```
pragma solidity ^0.4.21;

contract MyContract {
    function MyContract() public {
    }

    function lolWut() public returns(string) {
        return "lulwut";
    }
}
```

## Steps to reproduce
1. Above code
2. Compile and deploy
3. Press lolWut button

## Expected result
green button
lolwut

## Actual result
yellow button
Sorry, that page could not be found.

## Reproducible
I have a feeling we got a winner here

**Comment by javier-tarazaga** [comment]
Hi @Cygnusfear! 

Yeap I can see the issue. If you are trying to actually run a constant function, you need to add the constant modifier to the function like this: 

```js
 function lolWut() public constant returns(string) {
        return "lulwut";
    }
```

But anyway, the scenario you presented should not happen and we will need to check out what could be happening. 

Thanks for reporting it!

**Comment by Cygnusfear** [comment]
👍Yes, setting the proper modifier will fix the issue (constant/view etc)

**Comment by javier-tarazaga** [comment]
This issue was fixed in https://github.com/SuperblocksHQ/superblocks-lab/pull/105
