### ISSUE TITLE
Uncensorable newsfeed template contains errors

### ISSUE THREAD

**Issue by Bashlund** [SuperblocksHQ/superblocks-lab#103]
## Environment/Browser
Chromium

## Description
The Uncensorable Newsfeed template `app.js` file contains legacy code which make it throw an error.

## Steps to reproduce
1. Create new project using Uncensorable newsfeed
2. Compile and Deploy to browser network
3. Open the app preview window

## Expected result
No JS errors in console

## Actual result
JS error in console.
Due to `Contracts['Articles']` not existing 

## Reproducible
100%

## Fix
Remove the anonymous function `(function (Contract) {`, it's old legacy code.

**Comment by javier-tarazaga** [comment]
Fixed in https://github.com/SuperblocksHQ/superblocks-lab/pull/106
