### ISSUE TITLE
Compiler does not display the error for failure when contract name and filename does not match

### ISSUE THREAD

**Issue by Bashlund** [SuperblocksHQ/superblocks-lab#104]
## Environment/Browser
Chromium

## Description
When the contract inside the file `MyContract.sol` is named something else than `MyContract`, the compiler fails without stating what the error is, which is confusing.

## Steps to reproduce
1. Rename contract to something else than the filename.
2. Compile

## Expected result
To be told what the error actually is

## Actual result
Compiler only reports that the contract could not be compiled.

## Reproducible
100%

**Comment by javier-tarazaga** [comment]
Fixed in https://github.com/SuperblocksHQ/superblocks-lab/pull/107
