### ISSUE TITLE
You can't rename a Smart Contract until all the tabs are closed

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#110]
## Environment/Browser
Chrome 69.0.3497.81

## Description
You can't rename a Smart Contract until all the tabs are closed

## Steps to reproduce
1. Create a new Smart Contract
2. Create another Smart Contract and leave the tab open 
3. Try deleting the firstly created Smart Contract 

## Expected result
The Smart Contract gets actually deleted

## Actual result
An error message appears. You actually need to close all the tabs in order to be able to delete the contract. 

## Reproducible
100%

**Comment by filippsen** [comment]
Is it indeed *rename* or does it refer to *delete* instead ? I take that it refers to the latter.

**Comment by filippsen** [comment]
Changes to `delete` codepath (`src/components/projecteditor/control/control.js`) in https://github.com/Bashlund/superblocks-lab/commit/61729f8eb9da649ea5a4f4df25a33360cc886d7d, if merged in their entirety, will likely solve this issue. 

Please check again after #99 is done.

**Comment by filippsen** [comment]
Solved with request #168
