### ISSUE TITLE
The Gas limit cap is way too low for larger Smart Contracts

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#111]
## Environment/Browser
Chrome

## Description
The Gas limit cap it is way to low for larger Smart Contracts. Right now the cap is set to 390.000, therefore if you have a larger more complicated SC, you can't run it in the browser node. 

When using Metamask works just fine, as it overrides the max value we set. 

## Steps to reproduce
1. Create a SC which consumes a lot of Gas
2. Try to deploy to the browser

## Expected result
The SC gets deployed to the browser just fine

## Actual result
The deployment fails

## Reproducible
100%

**Comment by filippsen** [comment]
Relates to #150

**Comment by filippsen** [comment]
Relates to #151
