### ISSUE TITLE
New contract file only gets written to local storage after the first manual save action

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#135]
## Environment/Browser
Lab 1.0.0

## Description
New contract file only gets written to local storage after the very first save action.

## Steps to reproduce
1. Create a new file by clicking the _New contract_ button
2. Optionally reload the page
3. Observe the `dapps1.0.0` _Local Storage_ entry: the newly created contract will be missing
4. Observe the _Save_ icon in the editor menu bar will be marked as _red_ (unsaved changes).

## Expected result
Expected the newly created file to be present.

## Actual result
Newly created file is not saved until the user manually triggers the _Save_ action.

**Comment by javier-tarazaga** [comment]
Yeap, I do agree this is quite annoying. Whenever I create a new Smart Contract I expect it to be already saved.

**Comment by filippsen** [comment]
The current behavior is expected. There is a reason behind it:
> [Currently] [...] users are free to rename the contract before working on it. As long as it has never been saved, the stub contract will get the correct name as the use has given [to it]. As soon as saved and then renamed the user must rename the contract in the file [manually].

Changing this behavior has consequences:
> [...] a search and replace [could be applied] to help the user rename the `contract abc` in the file, but then [it would demand taking] responsibility of refactoring all occurrences in all other source files.

**Comment by filippsen** [comment]
Given,

a) changes to how storage works and how file operations are done after the transition to redux;
b) different general-purpose _New File_ action after the addition of the filesystem (instead of the specific _New contract_ button);
c) contracts stubs are not present anymore when creating a file with sol extension; 

the assumptions in the original report are no longer valid. 

The closest equivalents to the original _Steps to reproduce_ were applied for inspection. The results are:
1) Creating a _New File_ and reloading the page does maintain the file. That is a hint that newly created files are stored on the spot;
2) Creating a _New File_, closing the browser and then reopening the application does maintain file state. That is another hint that the newly created file is stored;
3) Creating a _New File_, downloading the project and inspecting the downloaded data shows the files are always present;
4) Observing the state before and after the _New File_ action and the involved state changes with `getContractsItem()`, the newly created file does appear as listed;
5) Observing the project `dappfile` data, it is possible to see updates being done on the spot, right after adding a new contract anywhere in the project structure.

Closing this issue as it has been resolved after the addition of the new filesystem in version `1.1.0` and the storage changes to file operation added in version version `1.3.0`.

@ostap1010, feel free to reopen in case there was anything else to be done that wasn't mentioned in this ticket.
