### ISSUE TITLE
Unable to click on highlighted area in Help/General links despite visual cue

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#137]
## Environment/Browser
Lab 1.0.0

## Description
Unable to click on the highlighted line to open links

## Steps to reproduce
![studio-issue-help-link](https://user-images.githubusercontent.com/697226/45300394-82987800-b50e-11e8-8466-77ba78d8f89f.jpg)

## Expected result
Expected to be able to click anywhere on the line to open the highlighted link.

## Actual result
The action only triggers when clicking on the text, despite the visual cue.

**Comment by javier-tarazaga** [comment]
Solved in #210
