### ISSUE TITLE
Change iframe's sandbox policy to enable Portis integration

### ISSUE THREAD

**Issue by itay-portis** [SuperblocksHQ/superblocks-lab#159]
## Summary
Portis is a platform that lets DApp users communicate with smart contracts and sign transactions, without installing anything. We need to change the iframe's sandbox policy to allow Portis to run in Lab.

## Motivation
With Portis users will be able to develop DApps within Lab without the need to install anything.
In addition, their DApps will be more accessible for the consumers.

## Additional context
In order to allow Portis integration, we'll need to change the iframe's sandbox policy and add this policy: `allow-same-origin`.

**Comment by javier-tarazaga** [comment]
This relates to #269 and the lack of localstorage in the AppPreview iframe

**Comment by javier-tarazaga** [comment]
This issue should be solved and was pushed to production.
