### ISSUE TITLE
Unable to see actions from left side menu when contract name is too long

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#164]
## Environment/Browser
Lab 1.0.0

## Description
Unable to see contract actions from the _Files_ hierarchy (left side menu) when contract name is too long (maximum length).
When selecting a contract (mouse over) of a particular length, with the standard GUI layout, the file name rendering is not restricted. The lack of restriction leads into an overlapping between the file name and action items (_Up_ and _Down_ arrows and the _Delete_ button).

## Steps to reproduce
1. Create _New contract_  named `1234567890123456`
2. Mouse over the `1234567890123456.sol` item, under _contracts_ in the _Files_ hierarchy

## Expected result
Expected the file name to adapt to the left side menu width.

## Actual result
<img width="274" alt="screen shot 2018-09-14 at 4 03 01 pm" src="https://user-images.githubusercontent.com/697226/45548437-9e5c9080-b824-11e8-9d06-e5c25e7707be.png">

## Hint
See #42 for similarities and possible solutions.

**Comment by javier-tarazaga** [comment]
Solved in #210
