### ISSUE TITLE
Change project download format from JSON to ZIP

### ISSUE THREAD

**Issue by Bashlund** [SuperblocksHQ/superblocks-lab#169]
## Summary

Now projects are downloaded as JSON files. These files are of no real use other than transferring/storing a project.

We can change the format to Zip - still using client side javascript - to let the user access/modify all files in the project in a sane way.

## Motivation

It will make so users can access and modify downloaded project files and also upload zip files containing project files.

## Describe alternatives you've considered

Another solution would be to have a helper script help the user extract the JSON into files on the filesystem.

## Additional context
There are a couple of libraries out there which does this neatly.
This issue would make sense to implement after #166 which will expose the full underlaying filesystem.

**Comment by javier-tarazaga** [comment]
Solved in #210
