### ISSUE TITLE
Enable arrays as constructor input

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#185]
## Environment/Browser
Lab 1.0.1

## Description
It is currently not possible to _Deploy_ a contract that takes an array as constructor parameters. There is no option for arrays in _Configure_.

### Example 1
```
pragma solidity ^0.4.21;

contract HelloWorld {
    address[] message;
    
    function HelloWorld(address[] initMessage) public {
        message.push(initMessage[0]);
    }
}
```

### Example 2
```
pragma solidity ^0.4.21;

contract HelloWorld {
    uint256[] public message;
    
    function HelloWorld(uint256[] initMessage) public {
        message = initMessage;
    }
}
```

## Expected result
Unable to configure parameters in _Configure_ window understandably leads into unsuccessful deployment.

## Actual result
>Constructor arguments given are not valid. Too many/few or wrong types.

>Constructor arguments given are not valid. Too many/few or wrong types. TypeError: value.forEach is not a function

**Comment by javier-tarazaga** [comment]
Not only is not possible to do so through the constructor configuration for the Smart Contract, but in fact, the tool at the moment does not support any form of interaction with the Smart Contract in which you pass an array as a parameter.

**Comment by filippsen** [comment]
Related: https://github.com/SuperblocksHQ/superblocks-lab/issues/186

**Comment by monkybrain** [comment]
@javier-tarazaga What's the status of this issue? I see that it's closed but I'm still getting the same behaviour, i.e. that you cannot pass arrays as _constructor_ arguments (function arguments seem to work fine!)

**Comment by javier-tarazaga** [comment]
Hi @monkybrain ! Sorry, the issue was closed but actually never released. We will be doing a new release hopefully tomorrow in which this feature will be included. 

Btw I highly recommend you to check out the 2.0 branch. A ton of changes and improvs are coming along the way!

**Comment by javier-tarazaga** [comment]
Btw will re-open the issue until we deploy it.

**Comment by monkybrain** [comment]
Great, thanks!

**Comment by monkybrain** [comment]
@javier-tarazaga Sorry to bother you again but I just tried the newly deployed release (`1.7.0`) and I still can't pass an array as constructor argument even though this issue is listed in the changelog. I still get the error `Constructor arguments given are not valid. Too many/few or wrong types. TypeError: e.forEach is not a function`.

**Comment by filippsen** [comment]
@monkybrain if you create a new project from the _Hello World_ template and paste in either one of the provided examples in this thread, then that error will occur. The reason for that to happen is that the constructor argument types in _Configure_ settings are not matching the contract code. The argument is likely set to a single `value` type instead of an `array`.  

In _Hello World_ template, it originally reads:
>No. args: 1
>(
>value Hello World!
>)

Notice the `value` argument type. There are different types available. Version `1.7.0` adds a new argument type specifically for arrays named `array`.

Using _Example 2_ - the `uint256[]` case from https://github.com/SuperblocksHQ/superblocks-lab/issues/185#issue-363204957 - one valid configuration could then be:
>No. args: 1
>(
>array 1, 3, 5, 7
>)

After that, _Deploy_ is expected to work:
```
Contract deployed at address 0x6831....
Done.
```

To verify it is working as intended,  go to _Interact_ and retrieve `message` by index. 
Example input:
```
message Arguments: 2
```
Expected output:
`5`

Would that be it ? If so, we should file a new issue to improve the error message or at least remove the undefined type error.

If that is not the case, could you please share the `constructor` code and the _Configure_ settings ? Thank you.

**Comment by javier-tarazaga** [comment]
Hi @monkybrain ! 

I just had a quick test and seems to be working on my side. Here you have a sample project with a constructor array working:

https://lab.superblocks.com/ipfs/QmdFM357xRoYVpTpeYEU8B1FTEX6VF5bWP9fuDWALvWai9

**Comment by monkybrain** [comment]
@filippsen Sorry, I didn't notice the new `array` field in the dropdown. Works fine for me too now! Thanks!

**Comment by filippsen** [comment]
All good! Marking as solved.
