### ISSUE TITLE
Enable arrays as input parameters when interacting with deployed contract

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#186]
## Environment/Browser
Lab 1.0.1

## Description
It is currently not possible to _Interact_ with a function that takes an array as input parameter.

## Steps to reproduce
```
pragma solidity ^0.4.21;

contract HelloWorld {
    uint256[] public messageNumbers;
    
    function HelloWorld() public {
    }

    function setMessage(uint256[] numbers) public  {
        messageNumbers = numbers;
    }
}
```

## Expected result
Expected to be able to call `setMessage` with a set of numbers as input.

## Actual result
`Error interacting with contract: TypeError: t.forEach is not a function`

**Comment by Spejbl** [comment]
Fixed in #203
