### ISSUE TITLE
OverFlow hashes of Transaction History while decreasing size

### ISSUE THREAD

**Issue by waheed25** [SuperblocksHQ/superblocks-lab#188]
## Environment/Browser
Lab 1.0.1

## Description
While decreasing the size of transaction history after some point hash of **Creator** and **Contract address** overflows from container of "Transaction history".
## Steps to reproduce
1.  Open "Transaction history" history.
2. Compile and deploy smart contract.
3. Start decreasing the size of "Transaction history".
4. While continuous decrease in size will produce horizontal scroll bar.
5. Scroll horizontally and you will see the overflow of hash.
<img width="440" alt="screen shot 2018-09-28 at 3 23 32 pm" src="https://user-images.githubusercontent.com/25927790/46209355-165ba800-c347-11e8-8eab-c077015845ff.png">

## Expected result
There should be overflow handling when container size is decreases on resizing.

## Actual result
Hash text overflows from container.
## Reproducible
100%

**Comment by Spejbl** [comment]
Solved in #300
