### ISSUE TITLE
Update babel presets as es2015 is deprecated

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#2]
Currently we are using `babel-preset-es2015": "^6.24.1",` and it was marked as deprecated. Update to `babel-preset-env` instead.

**Comment by filippsen** [comment]
Confirmed this is still being flagged as warning during `yarn install`

```
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```
