### ISSUE TITLE
Consider changing cursor state when hovering buttons in Interact window

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#208]
## Summary

![cursor-suggestion](https://user-images.githubusercontent.com/697226/47931383-f469be00-dece-11e8-8c1b-f6ec8ebcb3bd.jpg)

## Motivation

>It would be good if the cursor pointer changed to "clicking on a link" when hovering the buttons in _Interact_ mode.

**Comment by javier-tarazaga** [comment]
Solved in #210
