### ISSUE TITLE
Typos in Voting template

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#243]
## Environment/Browser
Version 1.1.0

## Description
In `app.js`:
- successfuly
- editin

**Comment by ianbritto** [comment]
I [submitted a PR](https://github.com/SuperblocksHQ/superblocks-lab/pull/258). Changes are inside a .zip file so diffs do not appear

**Comment by futurejones** [comment]
Templates in zip format needs to be changed. The source code is not viewable and changes can not be reviewed.

**Comment by ianbritto** [comment]
I know, they were already in zip format when I cloned. I just entered the zip, fixed the typos, saved and pushed back. Should I unzip and push or how should I proceed?  Changes were made correctly but we can't see the diffs because is in zip format. Thanks

**Comment by filippsen** [comment]
@futurejones thanks for your comments and suggestions. Please refer to Thomas' reply in request #260.

**Comment by filippsen** [comment]
@ianbritto the changes in #258 are good. Thank you!
