### ISSUE TITLE
Improve responsiveness so it works on smaller devices

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/superblocks-lab#255]
## Summary

Improve responsiveness of Lab, so it works smoothly on smaller devices and would be possible to embed it as an iframe on another websites.

## Motivation
![motivation](https://user-images.githubusercontent.com/17637244/48919309-4ed4b980-ee92-11e8-8fe9-25803d4e52e7.png)

We would like to embed Lab on another website. For example in tutorials where users can edit project without going to Lab. For this reason we need to make Lab more responsive so it works on smaller windows.

## Additional context

**What needs to be done**

- [x] Allow open panels (topbar) of files to be scrollable on one line
- [x] Transaction history should be resizable #88 
- [x] Fix transaction history - overflow of hashes #188 
- [x] On welcome screen hide unnecessary info (depends if we want to allow to create new projects in embedded window)
- [x] Overflow of account name's when too long
- [x] Hide bottom bar with yellow note on smaller devices
- [x] Modals shouldn't have a fixed width/height
- [x] Hide minimap in code editor (on the right side) on smaller devices
- [x] Learning and Resources navigation - auto collapsed on smaller devices
- [x] Adjust Configure account/contract window

**Needs discussion**

D1. What should be minimum viable width and height? 
D2. Should we allow mosaic view on smaller devices?

**Comment by filippsen** [comment]
Related issue, previously closed without a solution: https://github.com/SuperblocksHQ/superblocks-lab/issues/64

**Comment by filippsen** [comment]
I searched for "overflow" before filing an issue.
Noticed that lengthy account names are leaking. In case "Overflow of account name's when too long" or this request doesn't cover it already, here is what I see after copying the address to clipboard and pasting it as the account name:
![account_name_leak](https://user-images.githubusercontent.com/697226/51182726-5bdcba80-18cf-11e9-9226-d1debdf80ed3.jpg)
