### ISSUE TITLE
Importing a project as first action after loading won't work

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#263]
## Environment/Browser
Version 1.1.0. Last verified in version 1.4.3.

## Description
_Import_ as the very first action after loading the application won't work (NO OP). 

## Steps to reproduce
Set up: consider a set of projects already stored. After starting the application, it already starts with the last project open.

1. Click the top menu bar
2. Click _Import_
3. Load from src/templates/empty.zip

## Expected result
Expected Empty template import process to start, by asking questions (via alert boxes), etc.

## Actual result
It won't do anything on the first try (no errors).

**Comment by ostap1010** [comment]
Seems to be specific to old version of Chrome. Can be closed now.
