### ISSUE TITLE
Uncaught error when using web3.js 1.0.0-beta36

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#269]
## Environment/Browser
Version 1.1.0 (unconfirmed)

## Description
>I got an error when using `web3.js@1.0.0-beta.36` with Superblocks

## Steps to reproduce
Exact steps are unknown.

## Expected result
No error.

## Actual result
```
web3.min.js:
1 Uncaught DOMException: 
Failed to read the 'localStorage' property from 'Window': 
The document is sandboxed and lacks the 'allow-same-origin' flag.
```

**Comment by radotzki** [comment]
I believe that the best way to solve it is by host each Dapp on a separate subdomain, and then serve the hosted files with iframe. It will prevent cross-domain issues, and maintain the same security level.

**Comment by ostap1010** [comment]
This error does not occur anymore as app view is now running on subdomain and has access to own local storage.
