### ISSUE TITLE
Impossible to use IPFS from within AppView Iframe

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#274]
When inserting this code into hello world example at line 14, at the start of prototype.init.

(14) // Create the IPFS node instance 
const node = new window.Ipfs()

node.on('ready', () => { 
// Ready to use! 
// See https://github.com/ipfs/js-ipfs#core-api 
})

I get this from the console: 
"SecurityError: The operation is insecure. index.js:37 
./node_modules/level-js/index.js/</Level.prototype._open 
index.js:37 
./node_modules/level-js/node_modules/abstract-leveldown/abstract-leveldown.js/</AbstractLevelDOWN.prototype.open 
abstract-leveldown.js:36 
./node_modules/encoding-down/index.js/DB.prototype._open 
index.js:33 
./node_modules/abstract-leveldown/abstract-leveldown.js/</AbstractLevelDOWN.prototype.open 
abstract-leveldown.js:38 
./node_modules/deferred-leveldown/deferred-leveldown.js/DeferredLevelDOWN.prototype._open 
deferred-leveldown.js:19 
./node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js/</AbstractLevelDOWN.prototype.open 
abstract-leveldown.js:38 
./node_modules/levelup/lib/levelup.js/</LevelUP.prototype.open 
levelup.js:89 
LevelUP 
levelup.js:61 
LevelUP 
levelup.js:33 
LevelDatastore 
index.js:39 
createBackend 
backends.js:6 
IpfsRepo 
index.js:53 
./src/core/runtime/repo-browser.js/module.exports 
repo-browser.js:7 
IPFS 
index.js:73 
HelloWorld.prototype.init 
about:srcdoc:84:18 
HelloWorld.prototype.onReady 
about:srcdoc:181:5 
<anonymous> 
about:srcdoc:188:5 
mightThrow 
https://unpkg.com/jquery@3.3.1/dist/jquery.js:3534:21 
resolve/</process< 
https://unpkg.com/jquery@3.3.1/dist/jquery.js:3602:12"

Using <script src="https://unpkg.com/ipfs/dist/index.js"></script> as ipfs.js source in the html.

This might due to the fact that the iFrame is in the same origin as the app (and some flag restrictions when setting up the iFrame) because as soon as you actually download the DApp, it actually works as expected.

**Comment by javier-tarazaga** [comment]
This seems related to #269 and #159

**Comment by filippsen** [comment]
This is apparently dependent on browser settings, as the error differs on Chrome. The reported issue appears to have been caught when running on Firefox.

The references to database and potentially file system access hints for the need for those. I don't know what the exact library implementation details are or how to correctly make use of it on at the application level. 
What I could observe already is that running Chrome with `--allow-file-access-from-files` does not result in security error.

**Comment by ostap1010** [comment]
Works well now. Tested with adding file similar as in example: https://github.com/ipfs/js-ipfs/blob/master/examples/browser-script-tag/index.html.
