### ISSUE TITLE
Bump Solidity compiler version

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#30]
## Motivation

Update `solc` component, so contracts can take advantage of the latest libraries being written.

## Risks

1. Must be carefully reviewed when upgrading, due to the usual breaking changes added by external dependencies and possibly by the language itself.
2. This change has the potential to impact existing template contracts, at the very least.

**Comment by javier-tarazaga** [comment]
@filippsen how high in the priority list should we add this issue? I mean, how crucial this would be for someone actually using the tool? Any rough idea of the amount of work this would actually entitle?

**Comment by filippsen** [comment]
@javier-tarazaga this was a request from a "more advanced" developer.
It was mentioned it would be good to have the ability to either set to a specific compiler version (change) or have it set to the bleeding edge by default (latest). The idea was to take advantage of specific external libraries that target a different compiler version (newer).

Latest _Solidity_ language changes, applied in their respective compiler version, marked some things as deprecated, but code written in earlier versions is supposed to still be compatible (warnings). That said, it is apparently a non-blocking issue for newcomers using _Studio_ as base.

The process of updating the compiler itself is expected to be the same, as documented in `src/components/solc/README.md`. The big unknown is, apart from the already mentioned risks, doing extensive testing and dealing with externalities, which always happened in the past when dealing with those particular set of dependencies.

**Comment by javier-tarazaga** [comment]
@filippsen what about creating a collection of tests to run every time we bump a solidity version to make sure everything we spec to work, actually does work? This way we can mitigate a lot of risk involved in bumping versions.

**Comment by filippsen** [comment]
@javier-tarazaga I think some form of testing would be a healthy addition before proceeding, yes. That is, asserting the whole _Compile_ functionality is working as intended, which would indirectly include the `solc` part.

Please refer to #117, as it should be resolved before this one.

**Comment by filippsen** [comment]
See also: https://github.com/ethereum/solidity/blob/050-version/Changelog.md
