### ISSUE TITLE
Invalid Amplitude API key in release mode

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#317]
## Environment/Browser
Version 1.4.0 (request #305)

## Description
In release environment, the application logs a message about Amplitude API key being invalid.

## Steps to reproduce
1. `ORIGIN_DIST=localhost:3000 make dist`
2. `cd dist` 
3. `python2 -m SimpleHTTPServer 3000` (or any other server)
4. Browse to: `localhost:3000`
5. Observe browser console messages

## Expected result
Nothing.

## Actual result
The following regular log message appears in the browser console during load:
>[Amplitude] Invalid apiKey. Please set a valid apiKey with init() before calling logEvent()

## Question / possible hint
In `src/utils/analytics.js`, shouldn't the assignment in _Line 31_ be the other way around: unset key for development and set for release mode ?

**Comment by javier-tarazaga** [comment]
@filippsen indeed it is the other way around!
