### ISSUE TITLE
OpenZeppelin import should mention which version is being imported

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/superblocks-lab#380]
## Summary

> there’s no mention of which OpenZeppelin version is being imported. Supporting multiple versions might not be necessary, but at the very least users should know which one they are using

## Motivation

It would be nice to know which version is being imported, as there are new releases quite often

**Comment by javier-tarazaga** [comment]
Again, as we are already looking at having containers, we should aim for our users to use the `npm` dependency directly and not copy/paste the contracts in the app src folder directly.
