### ISSUE TITLE
OpenZeppelin contracts should be read-only

### ISSUE THREAD

**Issue by Spejbl** [SuperblocksHQ/superblocks-lab#381]
## Summary

> Code is being copy-pasted into the project. Users should not be allowed to easily modify OpenZeppelin code, since they may introduce errors that way - I’d go for making those source files read-only

Or at least show an alert before editing those contracts

**Comment by javier-tarazaga** [comment]
Is a really good point but looking at having the possibility of having containers in place, we should aim for our users to use npm dependencies and use directly the contracts from the `node_modules` folder instead, therefore eliminating the necessity to have read-only files.
