### ISSUE TITLE
Unable to access actions from top bar dropdown when project name and dapp titles are too long

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#42]
## Description
Unable to access _Edit DApp configuration_, _Download_ and _Delete_ buttons when project name and dapp titles are too long

## Steps to reproduce
1. Create a new project by accessing the top menu bar and clicking _Create New_
2. Set project name to `mmmmmmmmmmmmmmmmmmmm` or any other "lengthy" name
3. Set dapp title to `mmmmmmmmmmmmmmmmmmmm` or any other "lengthy" name
4. Confirm with `Next`
5. Choose any template e.g. Empty Project
6. Click _Create Project_
7. Open the top menu bar again

## Expected result
Expected to be able to access all the project actions regardless of the project name or dapp title length.

## Actual result
![studio-issue-long](https://user-images.githubusercontent.com/697226/44910796-d9d76500-ad24-11e8-9259-d0c4488789f8.jpg)

**Comment by filippsen** [comment]
Setting `.topbar.projectMenu.tabs.paneList.pane.projectSwitcherList.projSwitcherItem.max-width` in `src/components/topbar/style.less` to `600px` apparently provisions enough room for very long project title and name. 

However, such change must be double-checked to verify it doesn't have side effects considering it is set as an absolute value. Other style changes and alignment are also probably of related concern.

**Comment by javier-tarazaga** [comment]
@filippsen we could give the text div a max width which fits in the container, hide the overflow and add a text-overflow: ellipsis to the text.

**Comment by filippsen** [comment]
@waheed25 I updated the description with details and steps to reproduce the issue. Tks
