### ISSUE TITLE
Unable to edit custom account after setting it from seed

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#54]
## Description
Unable to edit, change or unlock a different _custom_ account after having unlocked it once.

## Steps to reproduce
1. Open any project or create a new one
2. Click the _Select an Account_ button by clicking the _Default_ account
3. Click the pencil icon to edit the _Default_ account
4. In the _Edit Account_ window, under the _Configure the account for each network_ section, select _custom_
5. Click the _Unlock_ button, inserting a valid seed e.g. `butter ...`

## Expected result
Expected to be able to reset, change or unlock a different custom account

## Actual result
There is no way to edit, change or unlock a different _custom_ account after having unlocked it once.

**Comment by filippsen** [comment]
Reloading _Studio_ resets unlocked accounts, which makes it the only way, at the moment, to reset and consequently set a _custom_ account from seed again.

**Comment by javier-tarazaga** [comment]
@filippsen can you provide info on how to test this fix?

**Comment by filippsen** [comment]
@javier-tarazaga the issue description has been edited to include the complete set of information.

Testing can be done by following the just added "Steps to reproduce" section.

The "actual result" will now be a button, positioned and styled just as the _Unlock_ one, but with a different label when a _custom_ account is already unlocked: 
> Unlock a different account 

Reminder: this was fixed in the referenced commit (0be056c).
