### ISSUE TITLE
"projects menu" overlays other components in top menu bar when resizing the window (width)

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#64]
## Actual result

![studio-alignment-issue-zoom100](https://user-images.githubusercontent.com/697226/44797940-a4116f80-abb0-11e8-8a9c-7e1c66a6fa60.jpg)

edit: added image as base reference

**Comment by filippsen** [comment]
Since the issue has to do with width, the obvious route for an improvement, without changing the style, would be to hide the "projects list" based on a minimum required width.

One idea to implement that: the `TopBar` could keep a state and set a `resize` event listener to update it. In `render`, the "projects list" `DropdownContainer` could take into account the minimum threshold before rendering.

Reference:
```
componentDidMount() {
    window.addEventListener('resize', this.onResizeEvent);
}
onResizeEvent() {
    this.setState({ width: window.innerWidth });
}
```

The aforementioned change would not take browser "zoom" into account, which would be a limitation. With zoom set to 67%, the width threshold would not render in the following case. At the end it wouldn't solve the problem completely:
![studio-alignment-issue-zoom67](https://user-images.githubusercontent.com/697226/44798604-35cdac80-abb2-11e8-87bc-86a7411713fe.jpg)

Another way could be to change the positioning parameters, perhaps setting it to absolute values instead of always being at the center, to more appropriately accommodate the different resolutions.

**Comment by javier-tarazaga** [comment]
@filippsen also I think this boils down who responsive we want the app to be. I the design does not scale for really small devices but that was the intended behavior.

**Comment by filippsen** [comment]
Small screens and resolutions are not supported at the moment.
