### ISSUE TITLE
New Dapp Flow - Grid layout is not responsive

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/superblocks-lab#83]
## Environment/Browser
Google Chrome 68.0.3440.106

## Description
When trying to create a new application using an existing template, the layout is not responsive therefore looks miss-aligned in larger screens. 

![screen shot 2018-08-30 at 10 43 18](https://user-images.githubusercontent.com/7814134/44840647-ca332000-ac41-11e8-823e-e1b26b9aa83f.png)

## Steps to reproduce
1. Create a new project and reach Step2 in the process. 
2. Try to select a template. Make sure to look at this screen in a big screen. 

## Expected result
The items in the grid adapt to the greater layout and render correctly. 

## Actual result
As seen in the attached screenshot, the grid is not rendering the items properly aligned.

## Reproducible
100%

**Comment by filippsen** [comment]
Solved with commit bb17c6de
