### ISSUE TITLE
Unable to change Transactions History container width

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/superblocks-lab#88]
## Description
You can't change the width of the Transactions container directly.

## Steps to reproduce
1. Open the _Transactions History_ container by clicking the _Transactions_ button (right side panel)
2. Try to resize the container with the cursor pointer

## Expected result
Expected to be able to resize the container width.

## Actual result
The container is fixed.

**Comment by filippsen** [comment]
Request #156 was completely reverted with #191 due to a bug that prevented actions in iframes from happening. Interacting with _Mosaic View_, _Show Preview_ and _Interact_ windows was not possible.

**Comment by Spejbl** [comment]
Solved in #313
